image:
  repository: htownmaniaacr.azurecr.io/houston-event-mania
  tag: latest
  pullPolicy: Always
envFromSecret: houston-event-mania-secrets
ingress:
  enabled: true
  className: nginx
  host: events.macdoncml.com
  tlsSecret: events-mania-tls
